package com.sample;
import javax.swing.JOptionPane
import javax.swing.JDialog
import javax.swing.JPanel
import javax.swing.JButton

declare Node
   question : String
   options: String []
   answer : String
end

function void setAnswerGUI(Node node) {
	int	response = JOptionPane.showOptionDialog(null, node.getQuestion(), null,
	        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
	        null, node.getOptions(), node.getOptions()[0]);
    if (response == -1)
		System.exit(-1);
    node.setAnswer(node.getOptions()[response]);
}

function void setAnswerGUIVertical(Node node, String message, String[] shortOptions) {
	int response = JOptionPane.showOptionDialog(null, message, null,
	        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
	        null, shortOptions, shortOptions[0]);
	if (response == -1)
		System.exit(-1);
    node.setAnswer(node.getOptions()[response]);
}

function void showFinalMessage(String message) {
	String[] options = {"OK"};
	int response = JOptionPane.showOptionDialog(null, message, null,
        JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,
        null, options, options[0]);
}
