package com.sample;

rule "CAN WE SEE YOUR LADY PARTS?"
    when
    	Node(question == "Choose question" && answer == "CAN WE SEE YOUR LADY PARTS?")
    then
    	Node node  = new Node();
        node.setQuestion("CAN WE SEE YOUR LADY PARTS");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);

    	insert(node);
end

rule "CAN WE SEE YOUR LADY PARTS? - NO - WELL DONE, CLASSY LADY. COVER THAT KITTY."
    when
        Node(question == "CAN WE SEE YOUR LADY PARTS" && answer == "NO")
    then
        showFinalMessage("WELL DONE, CLASSY LADY. COVER THAT KITTY.");
end

rule "CAN WE SEE YOUR LADY PARTS? - YES - YES, BUT ONLY IN BRIGHT LITGHT OR WHEN BEND OVER?"
    when
        Node(question == "CAN WE SEE YOUR LADY PARTS" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("YES, BUT ONLY IN BRIGHT LITGHT OR WHEN BEND OVER");
        String[] options = {"EXATLY"};
        node.setOptions(options);
        setAnswerGUI(node);

        insert(node);
end

rule "YES, BUT ONLY IN BRIGHT LITGHT OR WHEN BEND OVER? - EXATLY - PROCEED WITH CAUTION. SKIP DINNER WITH THE BOYFRIEND'S PARENTS."
    when
        Node(question == "YES, BUT ONLY IN BRIGHT LITGHT OR WHEN BEND OVER" && answer == "EXATLY")
    then
        showFinalMessage("PROCEED WITH CAUTION. SKIP DINNER WITH THE BOYFRIEND'S PARENTS.");
end

// -----------------------------------------------------------------------------
rule "DOES IT FALL PAST YOUR FINGER TIPS?"
    when
		Node(question == "Choose question" && answer == "DOES IT FALL PAST YOUR FINGER TIPS?")
    then
    	Node node  = new Node();
        node.setQuestion("DOES IT FALL PAST YOUR FINGER TIPS");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
	
    	insert(node);
end

rule "DOES IT FALL PAST YOUR FINGER TIPS? - NO - DID YOU DRY IT ON HIGH HEAT?"
    when
        Node(question == "DOES IT FALL PAST YOUR FINGER TIPS" && answer == "NO")        
    then
    	Node node  = new Node();
        node.setQuestion("DID YOU DRY IT ON HIGH HEAT");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
        
        insert(node);
end

rule "DID YOU DRY IT ON HIGH HEAT? - NO - NEXT TIME, TAKE A FRIEND SHOPPING. YOU GOT SERIOUSLY RIPPED OFF."
    when
        Node(question == "DID YOU DRY IT ON HIGH HEAT" && answer == "NO")
    then
        showFinalMessage("NEXT TIME, TAKE A FRIEND SHOPPING. YOU GOT SERIOUSLY RIPPED OFF.");
end

rule "DID YOU BUY IT FOR $20 FROM FOREVER 21? - YES - SORRY HUN THAT IS NO LONGER A DRESS."
    when
        Node(question == "DID YOU BUY IT FOR $20 FROM FOREVER 21" && answer == "YES")
    then
        showFinalMessage("SORRY HUN THAT IS NO LONGER A DRESS.");
end


rule "DID YOU DRY IT ON HIGH HEAT? - YES - DID YOU BUY IT FOR $20 FROM FOREVER 21?"
    when
        Node(question == "DID YOU DRY IT ON HIGH HEAT" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("DID YOU BUY IT FOR $20 FROM FOREVER 21");
        String[] options = {"YES", "NO"};
        node.setOptions(options);
        setAnswerGUI(node);
        
        insert(node);
end

rule "DOES IT FALL PAST YOUR FINGER TIPS? - YES - DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT?"
    when
        Node(question == "DOES IT FALL PAST YOUR FINGER TIPS" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT");
        String[] options = {"NO","YES"};
        node.setOptions(options);
        setAnswerGUI(node);
        
        insert(node);
end

rule "DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT? - NO - GURL, WORK THAT STUFF! YOU'RE DEFINITELY WEARING A DRESS."
    when
        Node(question == "DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT" && answer == "NO")
    then
        showFinalMessage("GURL, WORK THAT STUFF! YOU'RE DEFINITELY WEARING A DRESS.");
end

rule "DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT? - YES - THAT IS NOT A DRESS. ALSO MAKE A GYNO APPOINTMENT."
    when
        Node(question == "DOES YOUR TRUSH STICK TO THE SUBWAY SEAT WHEN YOU SIT" && answer == "YES")
    then
        showFinalMessage("THAT IS NOT A DRESS. ALSO MAKE A GYNO APPOINTMENT.");
end

//----------------------------------------------------------------------------------

rule "IS IT FLOWY AND HITS APPROXIMATELY MID"
    when
		Node(question == "Choose question" && answer == "IS IT FLOWY AND HITS APPROXIMATELY MID")
    then
    	Node node  = new Node();
        node.setQuestion("IS IT FLOWY AND HITS APPROXIMATELY MID");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "IS IT FLOWY AND HITS APPROXIMATELY MID - NO - ARE YOU GOING TO THE BEACH?"
    when
        Node(question == "IS IT FLOWY AND HITS APPROXIMATELY MID" && answer == "NO")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU GOING TO THE BEACH");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
        
        insert(node);
end

rule "ARE YOU GOING TO THE BEACH? - NO - HONEY, THAT'S A TUNIC NOT A DRESS. FIND SOME LEGGINS NEXT TIME."
    when
        Node(question == "ARE YOU GOING TO THE BEACH" && answer == "NO")
    then
        showFinalMessage("HONEY, THAT'S A TUNIC NOT A DRESS. FIND SOME LEGGINS NEXT TIME.");
end

rule "ARE YOU GOING TO THE BEACH? - YES - WELL ISN'T THAT FUN? YOU ENJOY THAT SUN!"
    when
        Node(question == "ARE YOU GOING TO THE BEACH" && answer == "YES")
    then
        showFinalMessage("WELL ISN'T THAT FUN? YOU ENJOY THAT SUN!");
end

rule "IS IT FLOWY AND HITS APPROXIMATELY MID - YES - ARE YOU BARE"
    when
        Node(question == "IS IT FLOWY AND HITS APPROXIMATELY MID" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU BARE");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);

        insert(node);
end

rule "ARE YOU BARE - NO - GURL, WORK THAT STUFF! YOU'RE DEFINITELY WEARING A DRESS."
    when
        Node(question == "ARE YOU BARE" && answer == "NO")
    then
        showFinalMessage("GURL, WORK THAT STUFF! YOU'RE DEFINITELY WEARING A DRESS.");
end

rule "ARE YOU BARE - YES - HONEY, THAT'S A TUNIC NOT A DRESS. FIND SOME LEGGINS NEXT TIME."
    when
        Node(question == "ARE YOU BARE" && answer == "YES")
    then
        showFinalMessage("HONEY, THAT'S A TUNIC NOT A DRESS. FIND SOME LEGGINS NEXT TIME.");
end

// --------------------------------------------------------------------------
rule "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP?"
    when
		Node(question == "Choose question" && answer == "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP?")
    then
    	Node node  = new Node();
        node.setQuestion("IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP");
        String[] options = {"NO", "YES", "MAYBE?"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP? - NO - WAY TO KNOW YOUR CLOTHING!"
    when
        Node(question == "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP" && answer == "NO")
    then
        showFinalMessage("WAY TO KNOW YOUR CLOTHING!");
end

rule "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP? - YES - TWO FACED CLOTHING SHOULD NEVER BE TRUSTED. DITCH IT FAST"
    when
        Node(question == "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP" && answer == "YES")
    then
        showFinalMessage("TWO FACED CLOTHING SHOULD NEVER BE TRUSTED. DITCH IT FAST");
end

rule "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP? - MAYBE? - WHEN IN DOUBT, THROW IT OUT."
    when
        Node(question == "IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP" && answer == "MAYBE?")
    then
        showFinalMessage("WHEN IN DOUBT, THROW IT OUT.");
end

// ---------------------------------------------------------------------------

rule "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES?"
    when
		Node(question == "Choose question" && answer == "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES?")
    then
		Node node  = new Node();
        node.setQuestion("ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES? - NO - MIGHT NOT BE DRESS RELATED. THROW SOME MAKEUP ON."
    when
        Node(question == "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES" && answer == "NO")
    then
        showFinalMessage("MIGHT NOT BE DRESS RELATED. THROW SOME MAKEUP ON.");
end


rule "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES? - YES - ARE YOU BEYONCE OR LADY GAGA?"
    when
        Node(question == "ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU BEYONCE OR LADY GAGA");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "ARE YOU BEYONCE OR LADY GAGA? - NO - LIKELY LINGERIE. YOU SAVE THAT FOR THE BEDROOM."
    when
        Node(question == "ARE YOU BEYONCE OR LADY GAGA" && answer == "NO")
    then
        showFinalMessage("LIKELY LINGERIE. YOU SAVE THAT FOR THE BEDROOM.");
end

rule "ARE YOU BEYONCE OR LADY GAGA? - YES - CONGRATS! WE ARE VERY JEALOUS."
    when
        Node(question == "ARE YOU BEYONCE OR LADY GAGA" && answer == "YES")
    then
        showFinalMessage("CONGRATS! WE ARE VERY JEALOUS.");
end

// -----------------------------------------------------------------------------------

rule "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?"
    when
		Node(question == "Choose question" && answer == "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?")
    then
    	Node node  = new Node();
        node.setQuestion("DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP? - NO - ARE YOU DOING A WALK OF SHAME?"
    when
        Node(question == "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP" && answer == "NO")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU DOING A WALK OF SHAME");
        String[] options = {"YES"};
        node.setOptions(options);
        setAnswerGUI(node);
            
        insert(node);
end

rule "ARE YOU DOING A WALK OF SHAME? - YES - SOMEONE HAD A FUN NIGHT! BETTER KEEP THAT DRESS FOR DIMLY LIT TIMES OF DAY."
    when
        Node(question == "ARE YOU DOING A WALK OF SHAME" && answer == "YES")
    then
        showFinalMessage("SOMEONE HAD A FUN NIGHT! BETTER KEEP THAT DRESS FOR DIMLY LIT TIMES OF DAY.");
end

rule "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP? - YES - ARE YOU MARILYN MONROE?"
    when
        Node(question == "DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU MARILYN MONROE");
        String[] options = {"NO", "YES"};
        node.setOptions(options);
        setAnswerGUI(node);

        insert(node);
end

rule "ARE YOU MARILYN MONROE? - NO - NO OK. GO HOME AND CHANGE"
    when
        Node(question == "ARE YOU MARILYN MONROE" && answer == "NO")
    then
        showFinalMessage("NO OK. GO HOME AND CHANGE");

end

rule "ARE YOU MARILYN MONROE? - YES - OOH, LOVE TATH PICTURE! GREAT WORK!"
    when
        Node(question == "ARE YOU MARILYN MONROE" && answer == "YES")
    then
        showFinalMessage("OOH, LOVE TATH PICTURE! GREAT WORK!");
end
