package com.sample;

rule "Initial question"
    when
    then
    	Node node = new Node();
    	node.setQuestion("Dress or pants");
    	String options[] = {"dress", "pants"};
    	node.setOptions(options);
    	setAnswerGUI(node);
    	
    	insert(node);
end


rule "Choose path dress"
    when
    	Node(question == "Dress or pants" && answer == "dress")
    then
    	Node node = new Node();
    	node.setQuestion("Choose question");
    	String[] options = {"CAN WE SEE YOUR LADY PARTS?",
    		"DOES IT FALL PAST YOUR FINGER TIPS?",
    		"IS IT FLOWY AND HITS APPROXIMATELY MID",
    		"IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP?",
    		"ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES?",
    		"DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?"
    	};
    	node.setOptions(options);
    	setAnswerGUI(node);
    	
    	insert(node);
end

rule "Choose path pants"
    when
    	Node(question == "Dress or pants" && answer == "pants")
    then
    	Node node = new Node();
    	node.setQuestion("Choose question");
    	String[] options = {"CAN WE SEE YOUR CRACK?",
    		"ARE THEY MADE OF DENIM?",
    		"DO THEY HAVE POCKETS?",
    		"ARE YOU SPORTING A CAMEL TOE?",
    		"ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?",
    		"CAN YOU WEAR THEM TO YOGA?"
    	};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

