package com.sample;

rule "Initial question"
    when
    then
    	Node node = new Node();
    	node.setQuestion("Dress or pants");
    	String options[] = {"dress", "pants"};
    	node.setOptions(options);
    	setAnswerGUI(node);
    	
    	insert(node);
end


rule "Choose path dress"
    when
    	Node(question == "Dress or pants" && answer == "dress")
    then
    	Node node = new Node();
    	node.setQuestion("Choose question");
    	String[] options = {"CAN WE SEE YOUR LADY PARTS?",
    		"DOES IT FALL PAST YOUR FINGER TIPS?",
    		"IS IT FLOWY AND HITS APPROXIMATELY MID-THIGH",
    		"IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP?",
    		"ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES?",
    		"DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?"
    	};
    	node.setOptions(options);
    	
    	String verticalMessage = "Choose question\n"+
    		"1: CAN WE SEE YOUR LADY PARTS?\n"+
    		"2: DOES IT FALL PAST YOUR FINGER TIPS?\n"+
    		"3: IS IT FLOWY AND HITS APPROXIMATELY MID-THIGH?\n"+
    		"4: IS IT POSSIBLE YOUR DRESS COULD ACTUALLY BE A TUBE TOP?\n"+
    		"5: ARE YOU GETTING AN UNUSUAL NUMBER OF WHISTLES?\n"+
    		"6: DO YOU FIND YOURSELF AVOIDING SEWER GRATES FOR FEAR YOUR DRESS WILL BLOW UP?";
    	String[] shortOptions = {"1", "2", "3", "4", "5", "6"};
    	setAnswerGUIVertical(node, verticalMessage, shortOptions);
    	
    	insert(node);
end

rule "Choose path pants"
    when
    	Node(question == "Dress or pants" && answer == "pants")
    then
    	Node node = new Node();
    	node.setQuestion("Choose question");
    	String[] options = {"CAN WE SEE YOUR CRACK?",
    		"ARE THEY MADE OF DENIM?",
    		"DO THEY HAVE POCKETS?",
    		"ARE YOU SPORTING A CAMEL TOE?",
    		"ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?",
    		"CAN YOU WEAR THEM TO YOGA?"
    	};
    	node.setOptions(options);
    	
    	String verticalMessage = "Choose question\n"+
    		"1: CAN WE SEE YOUR CRACK?\n"+
    		"2: ARE THEY MADE OF DENIM?\n"+
    		"3: DO THEY HAVE POCKETS?\n"+
    		"4: ARE YOU SPORTING A CAMEL TOE?\n"+
    		"5: ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?\n"+
    		"6: CAN YOU WEAR THEM TO YOGA?";
    	String[] shortOptions = {"1", "2", "3", "4", "5", "6"};
    	setAnswerGUIVertical(node, verticalMessage, shortOptions);

    	insert(node);
end

