package com.sample;

rule "CAN WE SEE YOUR CRACK?"
    when
		Node(question == "Choose question" && answer == "CAN WE SEE YOUR CRACK?")
    then
    	Node node  = new Node();
        node.setQuestion("CAN WE SEE YOUR CRACK");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);
		
    	insert(node);
end

rule "CAN WE SEE YOUR CRACK? - NO - EXCELLENT! CRACK IS WHACK."
    when
        Node(question == "CAN WE SEE YOUR CRACK" && answer == "NO")
    then
        showFinalMessage("EXCELLENT! CRACK IS WHACK.");
end

rule "CAN WE SEE YOUR CRACK? - YES - YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER?"
    when
        Node(question == "CAN WE SEE YOUR CRACK" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER");
    	String[] options = {"EXACTLY!"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER? - EXACTLY! - SORRY. BUT NO HONORABLE PAIR OF PANTS WOULD DO THAT TO YOU."
    when
        Node(question == "YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER" && answer == "EXACTLY!")
    then
        showFinalMessage("SORRY. BUT NO HONORABLE PAIR OF PANTS WOULD DO THAT TO YOU.");
end

// -------------------------------------------------------------------------------------------------

rule "ARE THEY MADE OF DENIM?"
    when
		Node(question == "Choose question" && answer == "ARE THEY MADE OF DENIM?")
    then
    	Node node  = new Node();
        node.setQuestion("ARE THEY MADE OF DENIM");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE THEY MADE OF DENIM? - NO - IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%?"
    when
        Node(question == "ARE THEY MADE OF DENIM" && answer == "NO")
    then
    	Node node  = new Node();
        node.setQuestion("IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%? - NO - THAT'S A GOOD SIGN!"
    when
        Node(question == "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%" && answer == "NO")
    then
        showFinalMessage("THAT'S A GOOD SIGN!");
end

rule "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%? - YES - ARE THEY CONTROL TOP"
    when
        Node(question == "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE THEY CONTROL TOP");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE THEY CONTROL TOP - YES - GAAAH, YOU'RE WEARING TIGHTS!"
    when
        Node(question == "ARE THEY CONTROL TOP" && answer == "YES")
    then
        showFinalMessage("GAAAH, YOU'RE WEARING TIGHTS!");
end

rule "ARE THEY CONTROL TOP - NO - THAT'S A GOOD SIGN!"
    when
        Node(question == "ARE THEY CONTROL TOP" && answer == "NO")
    then
         showFinalMessage("THAT'S A GOOD SIGN!");
end

rule "ARE THEY MADE OF DENIM? - YES - BE HONEST IS IT STRETCHY JEGGING DENIM?"
    when
        Node(question == "ARE THEY MADE OF DENIM" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("BE HONEST IS IT STRETCHY JEGGING DENIM");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "BE HONEST IS IT STRETCHY JEGGING DENIM? - NO - HUZZAH! YOU'RE PROBABLY WEARING PANTS."
    when
        Node(question == "BE HONEST IS IT STRETCHY JEGGING DENIM" && answer == "NO")
    then
        showFinalMessage("HUZZAH! YOU'RE PROBABLY WEARING PANTS.");
end

rule "BE HONEST IS IT STRETCHY JEGGING DENIM? - YES - JEGGINS ARE NOT PANTS. PLEASE PUT ON SOME PANTS."
    when
        Node(question == "BE HONEST IS IT STRETCHY JEGGING DENIM" && answer == "YES")
    then
        showFinalMessage("JEGGINS ARE NOT PANTS. PLEASE PUT ON SOME PANTS.");
end

// ---------------------------------------------------------------------------------------------

rule "DO THEY HAVE POCKETS?"
    when
		Node(question == "Choose question" && answer == "DO THEY HAVE POCKETS?")
    then
    	Node node  = new Node();
        node.setQuestion("DO THEY HAVE POCKETS");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);
		
    	insert(node);
end

rule "DO THEY HAVE POCKETS? - NO - ARE THEY SLACKS?"
    when
        Node(question == "DO THEY HAVE POCKETS" && answer == "NO")
    then
    	Node node  = new Node();
        node.setQuestion("ARE THEY SLACKS");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE THEY SLACKS? - NO - SOUND SUSPECT, THESE ARE LIKELY LEGGINGS, NOT PANTS."
    when
        Node(question == "ARE THEY SLACKS" && answer == "NO")
    then
        showFinalMessage("SOUND SUSPECT, THESE ARE LIKELY LEGGINGS, NOT PANTS.");
end

rule "ARE THEY SLACKS? - YES - LOOK AT YOU, MISS FANCY PANTS!"
    when
        Node(question == "ARE THEY SLACKS" && answer == "YES")
    then
        showFinalMessage("LOOK AT YOU, MISS FANCY PANTS!");
end


rule "DO THEY HAVE POCKETS? - YES - ARE THE POCKETS PAINTED ON IN GOLD GLITTER?"
    when
        Node(question == "DO THEY HAVE POCKETS" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE THE POCKETS PAINTED ON IN GOLD GLITTER");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE THE POCKETS PAINTED ON IN GOLD GLITTER? - YES - SOUNDS SUSPECT, THESE ARE LIKELY LEGGINGS NOT PANTS."
    when
        Node(question == "ARE THE POCKETS PAINTED ON IN GOLD GLITTER" && answer == "YES")
    then
        showFinalMessage("SOUNDS SUSPECT, THESE ARE LIKELY LEGGINGS NOT PANTS.");
end

rule "ARE THE POCKETS PAINTED ON IN GOLD GLITTER? - NO - HUZZAH! YOU'RE PROBABLY WEARING PANTS."
    when
        Node(question == "ARE THE POCKETS PAINTED ON IN GOLD GLITTER" && answer == "NO")
    then
        showFinalMessage("HUZZAH! YOU'RE PROBABLY WEARING PANTS.");
end

// ---------------------------------------------------------------------------------------

rule "ARE YOU SPORTING A CAMEL TOE?"
    when
		Node(question == "Choose question" && answer == "ARE YOU SPORTING A CAMEL TOE?")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU SPORTING A CAMEL TOE");
    	String[] options = {"NO", "YES", "MAYBE?"};
    	node.setOptions(options);
    	setAnswerGUI(node);
		
    	insert(node);
end

rule "ARE YOU SPORTING A CAMEL TOE? - NO - THANK GOODENESS!"
    when
        Node(question == "ARE YOU SPORTING A CAMEL TOE" && answer == "NO")
    then
        showFinalMessage("THANK GOODENESS!");
end

rule "ARE YOU SPORTING A CAMEL TOE? - YES - WHATEVER YOU'RE WEARING IS NOT YOUR FRIEND."
    when
        Node(question == "ARE YOU SPORTING A CAMEL TOE" && answer == "YES")
    then
        showFinalMessage("WHATEVER YOU'RE WEARING IS NOT YOUR FRIEND.");
end

rule "ARE YOU SPORTING A CAMEL TOE? - MAYBE? - NOT A GOOD SIGN! ASK AN HONEST FRIEND FOR THEIR OPINION."
    when
        Node(question == "ARE YOU SPORTING A CAMEL TOE" && answer == "MAYBE?")
    then
        showFinalMessage("NOT A GOOD SIGN! ASK AN HONEST FRIEND FOR THEIR OPINION.");
end

// -----------------------------------------------------------------------------------------------------


rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?"
    when
		Node(question == "Choose question" && answer == "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?")
    then
    	Node node  = new Node();
        node.setQuestion("ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR? - NO - PHEW! THAT WOULD BE EMBARASSING."
    when
        Node(question == "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR" && answer == "NO")
    then
        showFinalMessage("PHEW! THAT WOULD BE EMBARASSING.");
end

rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR? - YES - ARE YOU A LINGERINE MODEL?"
    when
        Node(question == "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU A LINGERINE MODEL");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE YOU A LINGERINE MODEL? - NO - PLEASE PUT ON SOME PANTS."
    when
        Node(question == "ARE YOU A LINGERINE MODEL" && answer == "NO")
    then
        showFinalMessage("PLEASE PUT ON SOME PANTS.");
end

rule "ARE YOU A LINGERINE MODEL? - YES - COOL JOB! PLEASE PUT PANTS ON BEFORE LEAVING WORK."
    when
        Node(question == "ARE YOU A LINGERINE MODEL" && answer == "YES")
    then
        showFinalMessage("COOL JOB! PLEASE PUT PANTS ON BEFORE LEAVING WORK.");
end

// -----------------------------------------------------------------------------------------------

rule "CAN YOU WEAR THEM TO YOGA?"
    when
		Node(question == "Choose question" && answer == "CAN YOU WEAR THEM TO YOGA?")
    then
    	Node node  = new Node();
        node.setQuestion("CAN YOU WEAR THEM TO YOGA");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "CAN YOU WEAR THEM TO YOGA? - NO - DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET?"
    when
        Node(question == "CAN YOU WEAR THEM TO YOGA" && answer == "NO")
    then
		Node node  = new Node();
        node.setQuestion("DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET");
    	String[] options = {"NO"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET? - NO - PATNS POTENTIAL = HIGH"
    when
        Node(question == "DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET" && answer == "NO")
    then
        showFinalMessage("PATNS POTENTIAL = HIGH");
end

rule "CAN YOU WEAR THEM TO YOGA? - YES - ARE YOU COMING FROM OR GOING TO YOGA?"
    when
        Node(question == "CAN YOU WEAR THEM TO YOGA" && answer == "YES")
    then
    	Node node  = new Node();
        node.setQuestion("ARE YOU COMING FROM OR GOING TO YOGA");
    	String[] options = {"NO", "YES"};
    	node.setOptions(options);
    	setAnswerGUI(node);

    	insert(node);
end

rule "ARE YOU COMING FROM OR GOING TO YOGA? - NO - MOST PANTS AREN'T DOWNWARD DOG FRIENDLY"
    when
        Node(question == "ARE YOU COMING FROM OR GOING TO YOGA" && answer == "NO")
    then
        showFinalMessage("MOST PANTS AREN'T DOWNWARD DOG FRIENDLY");
end

rule "ARE YOU COMING FROM OR GOING TO YOGA? - YES - NAMASTE."
    when
        Node(question == "ARE YOU COMING FROM OR GOING TO YOGA" && answer == "YES")
    then
        showFinalMessage("NAMASTE.");
end
