package com.sample;
import com.sample.Node
import com.sample.IOController

rule "CAN WE SEE YOUR CRACK?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then

        String question = "CAN WE SEE YOUR CRACK";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "CAN WE SEE YOUR CRACK? - NO - EXCELLENT! CRACK IS WHACK."
    when
        Node(q == "CAN WE SEE YOUR CRACK" && a == "NO")
    then
        IOController.print("EXCELLENT! CRACK IS WHACK.");
end

rule "CAN WE SEE YOUR CRACK? - YES - YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER?"
    when
        Node(q == "CAN WE SEE YOUR CRACK" && a == "YES")
    then
        String question = "YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER";
    	String[] choices = {"EXACTLY!"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER? - EXACTLY! - SORRY. BUT NO HONORABLE PAIR OF PANTS WOULD DO THAT TO YOU."
    when
        Node(q == "YES. BUT ONLY IN BRIGHT LIGHT OR WHEN YOU BEND OVER" && a == "EXACTLY!")
    then
        IOController.print("SORRY. BUT NO HONORABLE PAIR OF PANTS WOULD DO THAT TO YOU.");
end

// -------------------------------------------------------------------------------------------------

rule "ARE THEY MADE OF DENIM?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
        String question = "ARE THEY MADE OF DENIM";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE THEY MADE OF DENIM? - NO - IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%?"
    when
        Node(q == "ARE THEY MADE OF DENIM" && a == "NO")
    then
        String question = "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%? - NO - THAT'S A GOOD SIGN!"
    when
        Node(q == "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%" && a == "NO")
    then
        IOController.print("THAT'S A GOOD SIGN!");
end

rule "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%? - YES - ARE THEY CONTROL TOP"
    when
        Node(q == "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%" && a == "YES")
    then
        String question = "ARE THEY CONTROL TOP";
    	String[] choices = {"YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE THEY CONTROL TOP - YES - GAAAH, YOU'RE WEARING TIGHTS!"
    when
        Node(q == "ARE THEY CONTROL TOP" && a == "YES")
    then
        IOController.print("GAAAH, YOU'RE WEARING TIGHTS!");
end

rule "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%? - NO - ARE THEY CONTROL TOP"
    when
        Node(q == "IS THE LYCRA/SPANDEX % HIGHER THAN THE COTTON%" && a == "NO")
    then
        String question = "ARE THEY CONTROL TOP";
    	String[] choices = {"YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE THEY MADE OF DENIM? - YES - BE HONEST IS IT STRETCHY JEGGING DENIM?"
    when
        Node(q == "ARE THEY MADE OF DENIM" && a == "YES")
    then
        String question = "BE HONEST IS IT STRETCHY JEGGING DENIM";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "BE HONEST IS IT STRETCHY JEGGING DENIM? - NO - HUZZAH! YOU'RE PROBABLY WEARING PANTS."
    when
        Node(q == "BE HONEST IS IT STRETCHY JEGGING DENIM" && a == "NO")
    then
        IOController.print("HUZZAH! YOU'RE PROBABLY WEARING PANTS.");
end

rule "BE HONEST IS IT STRETCHY JEGGING DENIM? - YES - JEGGINS ARE NOT PANTS. PLEASE PUT ON SOME PANTS."
    when
        Node(q == "BE HONEST IS IT STRETCHY JEGGING DENIM" && a == "YES")
    then
        IOController.print("JEGGINS ARE NOT PANTS. PLEASE PUT ON SOME PANTS.");
end

// ---------------------------------------------------------------------------------------------

rule "DO THEY HAVE POCKETS?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
        String question = "DO THEY HAVE POCKETS";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "DO THEY HAVE POCKETS? - NO - ARE THEY SLACKS?"
    when
        Node(q  == "DO THEY HAVE POCKETS?" && a == "NO")
    then
        String question = "ARE THEY SLACKS";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE THEY SLACKS? - NO - SOUND SUSPECT, THESE ARE LIKELY LEGGINGS, NOT PANTS."
    when
        Node(q == "ARE THEY SLACKS" && a == "NO")
    then
        IOController.print("SOUND SUSPECT, THESE ARE LIKELY LEGGINGS, NOT PANTS.");
end

rule "ARE THEY SLACKS? - YES - LOOK AT YOU, MISS FANCY PANTS!"
    when
        Node(q == "ARE THEY SLACKS" && a == "YES")
    then
        IOController.print("LOOK AT YOU, MISS FANCY PANTS!");
end


rule "DO THEY HAVE POCKETS? - YES - ARE THE POCKETS PAINTED ON IN GOLD GLITTER?"
    when
        Node(q == "DO THEY HAVE POCKETS?" && a == "YES")
    then
        String question = "ARE THE POCKETS PAINTED ON IN GOLD GLITTER";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE THE POCKETS PAINTED ON IN GOLD GLITTER? - YES - SOUNDS SUSPECT, THESE ARE LIKELY LEGGINGS NOT PANTS."
    when
        Node(q == "ARE THE POCKETS PAINTED ON IN GOLD GLITTER" && a == "YES")
    then
        IOController.print("SOUNDS SUSPECT, THESE ARE LIKELY LEGGINGS NOT PANTS.");
end

rule "ARE THE POCKETS PAINTED ON IN GOLD GLITTER? - NO - HUZZAH! YOU'RE PROBABLY WEARING PANTS."
    when
        Node(q == "ARE THE POCKETS PAINTED ON IN GOLD GLITTER" && a == "NO")
    then
        IOController.print("HUZZAH! YOU'RE PROBABLY WEARING PANTS.");
end

// ---------------------------------------------------------------------------------------

rule "ARE YOU SPORTING A CAMEL TOE?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
        String question = "ARE YOU SPORTING A CAMEL TOE";
    	String[] choices = {"NO", "YES", "MAYBE?"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE YOU SPORTING A CAMEL TOE? - NO - THANK GOODENESS!"
    when
        Node(q == "ARE YOU SPORTING A CAMEL TOE" && a == "NO")
    then
        IOController.print("THANK GOODENESS!");
end

rule "ARE YOU SPORTING A CAMEL TOE? - YES - WHATEVER YOU'RE WEARING IS NOT YOUR FRIEND."
    when
        Node(q == "ARE YOU SPORTING A CAMEL TOE" && a == "YES")
    then
        IOController.print("WHATEVER YOU'RE WEARING IS NOT YOUR FRIEND.");
end

rule "ARE YOU SPORTING A CAMEL TOE? - MAYBE? - NOT A GOOD SIGN! ASK AN HONEST FRIEND FOR THEIR OPINION."
    when
        Node(q == "ARE YOU SPORTING A CAMEL TOE" && a == "MAYBE?")
    then
        IOController.print("NOT A GOOD SIGN! ASK AN HONEST FRIEND FOR THEIR OPINION.");
end

// -----------------------------------------------------------------------------------------------------


rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
        String question = "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR? - NO - PHEW! THAT WOULD BE EMBARASSING."
    when
        Node(q == "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR" && a == "NO")
    then
        IOController.print("PHEW! THAT WOULD BE EMBARASSING.");
end

rule "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR? - YES - ARE YOU A LINGERINE MODEL?"
    when
        Node(q == "ARE STRANGERS COMPLIMENTING ON YOUR UNDERWEAR" && a == "YES")
    then
        String question = "ARE YOU A LINGERINE MODEL";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE YOU A LINGERINE MODEL? - NO - PLEASE PUT ON SOME PANTS."
    when
        Node(q == "ARE YOU A LINGERINE MODEL" && a == "NO")
    then
        IOController.print("PLEASE PUT ON SOME PANTS.");
end

rule "ARE YOU A LINGERINE MODEL? - YES - COOL JOB! PLEASE PUT PANTS ON BEFORE LEAVING WORK."
    when
        Node(q == "ARE YOU A LINGERINE MODEL" && a == "YES")
    then
        IOController.print("COOL JOB! PLEASE PUT PANTS ON BEFORE LEAVING WORK.");
end

// -----------------------------------------------------------------------------------------------

rule "CAN YOU WEAR THEM TO YOGA?"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
        String question = "CAN YOU WEAR THEM TO YOGA";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "CAN YOU WEAR THEM TO YOGA? - NO - DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET?"
    when
        Node(q == "CAN YOU WEAR THEM TO YOGA" && a == "NO")
    then

        String question = "DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET";
    	String[] choices = {"NO"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET? - NO - PATNS POTENTIAL = HIGH"
    when
        Node(q == "DID YOU BUY THEM AT GAP BODY OR VICTORIA'S SECRET" && a == "NO")
    then
        IOController.print("PATNS POTENTIAL = HIGH");
end

rule "CAN YOU WEAR THEM TO YOGA? - YES - ARE YOU COMING FROM OR GOING TO YOGA?"
    when
        Node(q == "CAN YOU WEAR THEM TO YOGA" && a == "YES")
    then
        String question = "ARE YOU COMING FROM OR GOING TO YOGA";
    	String[] choices = {"NO", "YES"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);

    	insert(node);
end

rule "ARE YOU COMING FROM OR GOING TO YOGA? - NO - MOST PANTS AREN'T DOWNWARD DOG FRIENDLY"
    when
        Node(q == "ARE YOU COMING FROM OR GOING TO YOGA" && a == "NO")
    then
        IOController.print("MOST PANTS AREN'T DOWNWARD DOG FRIENDLY");
end

rule "ARE YOU COMING FROM OR GOING TO YOGA? - YES - NAMASTE."
    when
        Node(q == "ARE YOU COMING FROM OR GOING TO YOGA?" && a == "YES")
    then
        IOController.print("NAMASTE.");
end