package com.sample;
import com.sample.Node
import com.sample.IOController

rule "Initial question"
    when
    then
    	String question = "Dress or pants";
    	String[] choices = {"dress", "pants"};
    	String answer = IOController.askQuestion(question, choices);
		Node node = new Node(question, answer);
    	insert(node);
end

rule "Dress exists"
    when
    	Node(q == "Dress or pants" && a == "dress")
    then
    	IOController.print("Dress exists");
end

rule "Pants exist"
    when
    	Node(q == "Dress or pants" && a == "pants")
    then
    	IOController.print("Pants exist");
end
